services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: blog_application
      MYSQL_ROOT_PASSWORD: myorcriss
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:myorcriss@db:3306/blog_application  # Updated to match
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "8501:8501"
    environment:
      API_BASE: http://backend:8000
    depends_on:
      - backend

volumes:
  mysql_data: